### PR TITLE
Disable re render of Button Component

### PR DESCRIPTION
**Pull request by cjharkins**

### CODE REVIEW

**Comment by chetanraj** [comment]
@cjharkins - Thanks for the PR, Can you remove the .idea folder and update the PR

**Comment by cjharkins** [comment]
PR updated @chetanraj

**Comment by chetanraj** [comment]
@cjharkins - Still the Button is re-rendering, just put a console.log in that and check once, The `shouldComponentUpdate`  in Snippet component, avoids re-rendering of that component.

I tried using a `memo` also, no luck.

**Comment by cjharkins** [comment]
@chetanraj Made Button class based to utilize shouldComponentUpdate.

Button renders only once now. :)

**Pull request merged**
