### PR TITLE
add a few example for Vue directives

### PR DESCRIPTION
**Pull request by mhadaily**
this should cover this issue https://github.com/chetanraj/snpt/issues/14

### CODE REVIEW

**Comment by chetanraj** [comment]
Thanks, Please resolve the conflicts and update the PR.

**Comment by mhadaily** [comment]
@chetanraj done

**Comment by mhadaily** [comment]
I have not seen any feedbacks from you. Would be nice to hear something.

**Comment by chetanraj** [comment]
The Vue snippets from you were good, I needed straight forward and simple ones, Actually I've update the Vue, please have a look once..

**Pull request closed without merging**
